name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and prepare for test
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools --upgrade
        python -m pip install flake8
        sudo apt-get install busybox
        sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    - name: Test
      run: |
        make test
